version: "3.8"

services:
  db:
    image: postgres
    container_name: local_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user_crypto
      POSTGRES_PASSWORD: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918

    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container2
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user_crypto@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
